version: '3.3'
services:

    php:
         image: chialab/php:7.4-fpm
         working_dir: /var/www/translator
         volumes:
            - ./:/var/www/translator/
         restart: always

    mysql:
         image: mysql:8.0.16
         command: --default-authentication-plugin=mysql_native_password
         environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: test
         restart: always
